language: objective-c
osx_image: xcode10
install: true # skip pod install; all dependencies are already in the repo
script:
  - xcodebuild test -workspace Awful.xcworkspace -scheme Awful -destination 'platform=iOS Simulator,name=iPhone 8'
notifications:
  email:
    - nolan@nolanw.ca
    - liamwestby@icloud.com
