language: objective-c
before_install:
  - brew update
  - brew install xctool || brew upgrade xctool
script: xctool -workspace Awful.xcworkspace -scheme 'Awful App Store' -sdk iphonesimulator test
notifications:
  email:
    - nolan@nolanw.ca
