language: objective-c
before_install:
  - brew update
  - brew install xctool || brew upgrade xctool
install: true # skip cocoapods
script: xctool test
notifications:
  email:
    - nolan@nolanw.ca

branches:
  except:
    - master # until Xcode 6 shows up
