os: osx
osx_image: xcode10
install:
  - touch Local.xcconfig
script:
  - xcodebuild test -workspace Awful.xcworkspace -scheme Awful -destination 'platform=iOS Simulator,name=iPhone 8'
notifications:
  email:
    - nolan@nolanw.ca
    - liamwestby@icloud.com
