exclude:
  - Awful.xcodeproj
  - CNAME
  - README.md
  - Rakefile
  - Scripts
  - Source
  - Tests
  - Vendor
  # Lame way to exclude Resources except Resources/{Thread Tags,Icons}
  - Awful-Info.plist
  - Browsers.plist
  - Custom CSS README.txt
  - Default
  - Forum Abbreviations.plist
  - Images
  - Settings.plist
  - Theming
  - licenses.html
