pool:
  vmImage: 'macOS-10.14'

steps:
- task: Xcode@5
  inputs:
    actions: 'test'
    configuration: 'Debug'
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 8'
    destinationTypeOption: 'simulators'
    scheme: 'Awful'
    sdk: 'iphonesimulator13.0'
    useXcpretty: false
    xcWorkspacePath: 'Awful.xcworkspace'
    xcodeVersion: '11'
